services:
  db:
    image: mysql:8.0.45-debian
    container_name: ecommerce_mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - ecommerce

networks:
  ecommerce:
    driver: bridge

volumes:
  db-data:
