library: "spring-boot"
modelPackage: "xyz.peasfultown.ecommerce.product_api.model"
apiPackage: "xyz.peasfultown.ecommerce.product_api"
invokerPackage: "xyz.peasfultown.ecommerce.product_api"
dateLibrary: "java8"
unhandledException: true
sourceFolder: "src/main/java"
resourceFolder: "src/main/resources"
useBeanValidation: true
useJakartaEe: true
useSpringBoot3: true
useTags: true
generateBuilders: true
serializableModel: true
useSwaggerUI: true
