openapi: 3.0.1
info:
  title: E-Commerce Inventory Service
  description: |
    Handles the product inventory management part of the e-commerce microservices platform
  contact:
    email: emrin4@gmail.com
  license:
    name: MIT
    url: https://mit-license.org/
  version: 0.0.1

tags:
  - name: inventory
    description: Product inventory management

paths:
  /api/v1/inventory:
    get:
      tags: [ inventory ]
      summary: Get all inventory
      operationId: getAllProductInventory
      parameters:
        - $ref: '#/components/parameters/PageNumber'
        - $ref: '#/components/parameters/PageSize'
      responses:
        '200':
          description: Successful read
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedInventoryResponse'

  /api/v1/inventory/{productId}:
    get:
      tags: [ inventory ]
      summary: Get inventory for product by ID
      operationId: getProductInventoryByProductId
      parameters:
        - $ref: '#/components/parameters/ProductIdPath'
      responses:
        '200':
          description: Successful read
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Inventory'
        '404':
          description: Product not found by ID



    put:
      tags: [ inventory ]
      summary: Update product stock (admin)
      operationId: updateProductInventoryById
      parameters:
        - $ref: '#/components/parameters/UserRoleHeader'
        - $ref: '#/components/parameters/ProductIdPath'
      requestBody:
        description: Update request object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateInventoryReq'
      responses:
        '204':
          description: Successful update
          content: {}
        '404':
          description: Product not found by ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/inventory/low-stock:
    get:
      tags: [ inventory ]
      summary: Get all low stock products (admin)
      operationId: getLowStockProducts
      parameters:
        - $ref: '#/components/parameters/UserRoleHeader'
        - $ref: '#/components/parameters/PageNumber'
        - $ref: '#/components/parameters/PageSize'
      responses:
        '200':
          description: Successful read
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedInventoryResponse'

  /api/v1/inventory/out-of-stock:
    get:
      tags: [ inventory ]
      summary: Get all out of stuck products (admin)
      operationId: getOutOfStockProducts
      parameters:
        - $ref: '#/components/parameters/UserRoleHeader'
        - $ref: '#/components/parameters/PageNumber'
        - $ref: '#/components/parameters/PageSize'
      responses:
        '200':
          description: Successful read
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedInventoryResponse'

components:

  parameters:

    UserIdHeader:
      name: X-User-Id
      in: header
      required: true
      schema:
        type: string

    UserRoleHeader:
      name: X-User-Role
      in: header
      required: true
      schema:
        type: string
        enum:
          - ADMIN
          - CUSTOMER

    ProductIdPath:
      name: productId
      in: path
      required: true
      schema:
        type: string

    PageNumber:
      name: page
      in: query
      schema:
        type: integer
        format: int32
        default: 0

    PageSize:
      name: size
      in: query
      schema:
        type: integer
        format: int32
        default: 10

  schemas:

    ErrorResponse:
      type: object
      properties:
        status:
          type: integer
        error:
          type: string
        message:
          type: string
        path:
          type: string
        timestamp:
          type: string
          format: date-time
      required: [ status, message ]

    ResponsePage:
      type: object
      properties:
        number:
          type: integer
          format: int32
        size:
          type: integer
          format: int32
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
          format: int32

    PagedResponse:
      type: object
      properties:
        content:
          type: array
          items: {}
        page:
          $ref: '#/components/schemas/ResponsePage'

    PagedInventoryResponse:
      allOf:
        - $ref: '#/components/schemas/PagedResponse'
        - type: object
          properties:
            content:
              type: array
              items:
                $ref: '#/components/schemas/Inventory'

    Inventory:
      type: object
      properties:
        productId:
          type: string
        stock:
          type: integer
          format: int64

    UpdateInventoryReq:
      type: object
      properties:
        stock:
          type: integer
          format: int64